"""Our own writer of the game's model files for a static prop: .mdl (version 49, L4D2), .vvd (vertices,
version 4) and .dx90.vtx (triangle lists, version 7), laid out the way studiomdl lays out a one-bone static
prop (measured from its output; structures from Source SDK 2013 public/studio.h and optimize.h, read as the
game's 32-bit on-disk layout). The collision model (.phy) still comes from studiomdl; its checksum must
match the other three, so build() takes it.

Coordinates are model space as the game uses it (the same axes as Blender's object space: no turn, unlike
studiomdl's SMD input). Texture V runs top-down (1 - Blender's v).
"""
from __future__ import annotations

import struct

MDL_VERSION, VVD_VERSION, VTX_VERSION = 49, 4, 7
STUDIOHDR_FLAGS_STATIC_PROP, STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX = 0x10, 0x1
BONE_USED_BY_HITBOX, BONE_USED_BY_VERTEX_LOD0 = 0x100, 0x400
STRIPGROUP_IS_HWSKINNED, STRIP_IS_TRILIST = 0x2, 0x1
HULL_PAD = 0.25            # the movement hull and sequence box are the mesh's box grown by this (measured)


def _pad4(b: bytearray):
    b.extend(b"\0" * (-len(b) % 4))


class _Strings:
    """The string table at the end of the .mdl: each user remembers where its offset goes, relative to
    the start of the structure that holds it."""
    def __init__(self):
        self.items: list[tuple[str, int, int]] = []        # (text, where the int goes, base it's relative to)

    def ref(self, text: str, at: int, base: int):
        self.items.append((text, at, base))

    def write(self, out: bytearray, placed: dict[str, int]):
        """Append the strings not already in placed (text -> offset) and fill in every reference."""
        for text, at, base in self.items:
            if text not in placed:
                placed[text] = len(out)
                out.extend(text.encode("latin-1") + b"\0")
            struct.pack_into("<i", out, at, placed[text] - base)


def _tangents(verts, tris):
    """Per-vertex tangent (x, y, z, handedness) from the UVs, as the game's normal mapping expects."""
    acc = [[0.0, 0.0, 0.0] for _ in verts]
    bit = [[0.0, 0.0, 0.0] for _ in verts]
    for a, b, c in tris:
        (p0, _, t0), (p1, _, t1), (p2, _, t2) = verts[a], verts[b], verts[c]
        e1 = [p1[i] - p0[i] for i in range(3)]
        e2 = [p2[i] - p0[i] for i in range(3)]
        du1, dv1 = t1[0] - t0[0], t1[1] - t0[1]
        du2, dv2 = t2[0] - t0[0], t2[1] - t0[1]
        r = du1 * dv2 - du2 * dv1
        if abs(r) < 1e-12:
            continue
        r = 1.0 / r
        sdir = [(e1[i] * dv2 - e2[i] * dv1) * r for i in range(3)]
        tdir = [(e2[i] * du1 - e1[i] * du2) * r for i in range(3)]
        ls = sum(x * x for x in sdir) ** 0.5 or 1.0         # each triangle counts the same (as studiomdl)
        lt = sum(x * x for x in tdir) ** 0.5 or 1.0
        sdir = [x / ls for x in sdir]
        tdir = [x / lt for x in tdir]
        for v in (a, b, c):
            for i in range(3):
                acc[v][i] += sdir[i]
                bit[v][i] += tdir[i]
    out = []
    for (p, n, _t), t, bt in zip(verts, acc, bit):
        d = sum(n[i] * t[i] for i in range(3))
        t = [t[i] - n[i] * d for i in range(3)]
        ln = sum(x * x for x in t) ** 0.5
        if ln < 1e-12:                      # no UV direction: any vector across the normal
            t = [1.0, 0.0, 0.0] if abs(n[0]) < 0.9 else [0.0, 1.0, 0.0]
            d = sum(n[i] * t[i] for i in range(3))
            t = [t[i] - n[i] * d for i in range(3)]
            ln = sum(x * x for x in t) ** 0.5
        t = [x / ln for x in t]
        cx = (n[1] * t[2] - n[2] * t[1], n[2] * t[0] - n[0] * t[2], n[0] * t[1] - n[1] * t[0])
        w = -1.0 if sum(cx[i] * bt[i] for i in range(3)) < 0 else 1.0
        out.append((t[0], t[1], t[2], w))
    return out


def _meshes(triangles):
    """Group triangles by material, each mesh with its own vertex list (identical corners shared).
    triangles: [(material, (vertex, vertex, vertex))], vertex = (pos, normal, uv with Blender's v)."""
    meshes: dict[str, tuple[list, dict, list]] = {}
    for material, tri in triangles:
        verts, index, tris = meshes.setdefault(material, ([], {}, []))
        ids = []
        for p, n, (u, v) in tri:
            key = (tuple(round(c, 5) for c in p), tuple(round(c, 5) for c in n), (round(u, 6), round(1.0 - v, 6)))
            if key not in index:
                index[key] = len(verts)
                verts.append(key)
            ids.append(index[key])
        tris.append(tuple(ids))
    return [(m, verts, tris) for m, (verts, _i, tris) in meshes.items()]


def build(name: str, triangles, materials_dir: str, surfaceprop: str, mass: float, checksum: int,
          static: bool = True) -> dict[str, bytes]:
    """The .mdl, .vvd and .dx90.vtx of a one-bone prop. name: 'hammerless/<map>/<model>' (no .mdl)."""
    meshes = _meshes(triangles)
    all_verts = [v for _m, verts, _t in meshes for v in verts]
    if not all_verts:
        raise ValueError(f"model {name} has no triangles")
    lo = [min(v[0][i] for v in all_verts) for i in range(3)]
    hi = [max(v[0][i] for v in all_verts) for i in range(3)]
    return {".vvd": _vvd(meshes, checksum), ".dx90.vtx": _vtx(meshes, checksum),
            ".mdl": _mdl(name, meshes, materials_dir, surfaceprop, mass, checksum, lo, hi, static)}


def _vvd(meshes, checksum) -> bytes:
    verts, tangents = [], []
    for _m, mv, tris in meshes:
        verts += mv
        tangents += _tangents(mv, tris)
    n = len(verts)
    out = bytearray(struct.pack("<4siii8iiiii", b"IDSV", VVD_VERSION, checksum, 1, *([n] * 8), 0, 64, 64, 64 + 48 * n))
    for p, nm, uv in verts:
        out += struct.pack("<3f3bB3f3f2f", 1.0, 0.0, 0.0, 0, 0, 0, 1, *p, *nm, *uv)
    for t in tangents:
        out += struct.pack("<4f", *t)
    return bytes(out)


def _vtx(meshes, checksum) -> bytes:
    nmesh = len(meshes)
    head = 36
    bodypart = head
    model = bodypart + 8
    lod = model + 8
    mesh0 = lod + 12
    group0 = mesh0 + 9 * nmesh
    out = bytearray(group0 + 25 * nmesh)
    struct.pack_into("<iiHHiiiiii", out, 0, VTX_VERSION, 24, 53, 9, 3, checksum, 1, 0, 1, bodypart)
    struct.pack_into("<ii", out, bodypart, 1, model - bodypart)
    struct.pack_into("<ii", out, model, 1, lod - model)
    struct.pack_into("<iif", out, lod, nmesh, mesh0 - lod, 0.0)
    for i, (_m, verts, tris) in enumerate(meshes):
        mp, gp = mesh0 + 9 * i, group0 + 25 * i
        struct.pack_into("<iiB", out, mp, 1, gp - mp, 0)
        strip = len(out)
        out += bytearray(27)
        vstart = len(out)
        for k in range(len(verts)):
            out += struct.pack("<3BBH3b", 0, 1, 2, 0, k, 0, 0, 0)
        istart = len(out)
        indices = [i for a, b, c in tris for i in (a, c, b)]       # the game's front faces wind clockwise
        out += struct.pack(f"<{len(indices)}H", *indices)
        end = len(out)
        struct.pack_into("<iiiiiiB", out, gp, len(verts), vstart - gp, len(indices), istart - gp, 1, strip - gp,
                         STRIPGROUP_IS_HWSKINNED)
        struct.pack_into("<iiiihBii", out, strip, len(indices), 0, len(verts), 0, 0, STRIP_IS_TRILIST, 0, end - strip)
    out += bytearray(8)                       # (measured: 8 bytes before the material replacement lists)
    struct.pack_into("<i", out, 24, len(out))
    out += struct.pack("<ii", 0, 0)           # LOD 0: no material replacements
    return bytes(out)


def _mdl(name, meshes, materials_dir, surfaceprop, mass, checksum, lo, hi, static) -> bytes:
    nmesh = len(meshes)
    out = bytearray(408)
    S = _Strings()

    hdr2 = len(out)
    out += bytearray(256)

    bone = len(out)
    out += bytearray(216)
    struct.pack_into("<ii6i3f4f3f3f3f12f4fiiiiii", out, bone, 0, -1, *([-1] * 6), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
                     0.0, 0.0, 0.0, 0.003906369209289551, 0.003906369209289551, 0.003906369209289551,
                     1.1984590855718125e-05, 1.1984590855718125e-05, 1.1984590855718125e-05,
                     1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
                     0.0, 0.0, 0.0, 0.0, BONE_USED_BY_HITBOX | BONE_USED_BY_VERTEX_LOD0, 0, 0, 0, 0, 1)
    S.ref("static_prop", bone, bone)
    S.ref(surfaceprop, bone + 176, bone)                                    # surfacepropidx

    hitboxset = len(out)
    out += bytearray(12)
    bbox = len(out)
    out += bytearray(68)
    struct.pack_into("<ii", out, hitboxset + 4, 1, bbox - hitboxset)
    S.ref("default", hitboxset, hitboxset)
    struct.pack_into("<ii3f3f", out, bbox, 0, 0, *lo, *hi)
    S.ref("", bbox + 32, bbox)                                              # hitbox name

    bonetable = len(out)
    out += b"\0\0\0\0"

    anim = len(out)
    out += bytearray(100)
    out += bytearray(8) + struct.pack("<BBh", 255, 0, 0)                     # no bone animated
    struct.pack_into("<ii f iiii", out, anim, -anim, 0, 30.0, 0, 1, 0, 0)
    struct.pack_into("<i", out, anim + 56, 108)                             # animindex (after animblock)
    S.ref("@idle", anim + 4, anim)

    hlo = [c - HULL_PAD for c in lo]
    hhi = [c + HULL_PAD for c in hi]
    seq = len(out)
    out += bytearray(212)
    weights = len(out)
    out += struct.pack("<f", 1.0)
    animidx = len(out)
    out += struct.pack("<hh", 0, 0)
    struct.pack_into("<iiiiiiii3f3fiii2i2i2f2fiffiiifffii", out, seq, -seq, 0, 0, 0, -1, 0, 0, 212, *hlo, *hhi,
                     1, animidx - seq, 0, 1, 1, -1, -1, 0.0, 0.0, 0.0, 0.0, 0, 0.2, 0.2, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0)
    # numikrules, numautolayers, autolayerindex, weightlistindex, posekeyindex, numiklocks, iklockindex,
    # keyvalueindex, keyvaluesize, cycleposeindex, activitymodifierindex, numactivitymodifiers
    struct.pack_into("<12i", out, seq + 144, 0, 0, weights - seq, weights - seq, 0, 0, animidx - seq,
                     animidx + 4 - seq, 0, 0, 0, 0)
    S.ref("idle", seq + 4, seq)
    S.ref("", seq + 8, seq)

    bodypart = len(out)
    out += bytearray(16)
    model = len(out)
    out += bytearray(148)
    mesh0 = len(out)
    out += bytearray(116 * nmesh)
    struct.pack_into("<iiii", out, bodypart, 0, 1, 1, model - bodypart)
    S.ref("body", bodypart, bodypart)
    total = sum(len(v) for _m, v, _t in meshes)
    struct.pack_into("<64sifiiiiiiiii", out, model, b"model.smd", 0, 0.0, nmesh, mesh0 - model, total, 0, 0, 0, 0, 0,
                     mesh0 + 116 * nmesh - model)
    first = 0
    for i, (_m, verts, _t) in enumerate(meshes):
        mp = mesh0 + 116 * i
        struct.pack_into("<iiiiiiiii3f", out, mp, i, model - mp, len(verts), first, 0, 0, 0, 0, i, 0.0, 0.0, 0.0)
        struct.pack_into("<8i", out, mp + 52, *([len(verts)] * 8))
        first += len(verts)

    texture = len(out)
    out += bytearray(64 * nmesh)
    for i, (m, _v, _t) in enumerate(meshes):
        S.ref(m, texture + 64 * i, texture + 64 * i)
    cd = len(out)
    out += bytearray(4)
    S.ref(materials_dir.replace("/", "\\"), cd, 0)
    skin = len(out)
    out += struct.pack(f"<{nmesh}h", *range(nmesh))
    _pad4(out)

    keyvalue = len(out)                        # the string table: "" first, then the surface property
    out += b"\0"
    surf = len(out)
    out += surfaceprop.encode("latin-1") + b"\0"
    S.write(out, {"": keyvalue, surfaceprop: surf})
    _pad4(out)

    flags = (STUDIOHDR_FLAGS_STATIC_PROP if static else 0) | STUDIOHDR_FLAGS_AUTOGENERATED_HITBOX
    nm = name if name.endswith(".mdl") else name + ".mdl"
    illum = [(lo[i] + hi[i]) / 2 for i in range(3)]                  # lighting is sampled at the box's middle
    struct.pack_into("<4sii64si3f3f3f3f3f3fi", out, 0, b"IDST", MDL_VERSION, checksum, nm.encode("latin-1"), len(out),
                     0, 0, 0, *illum, *hlo, *hhi, 0, 0, 0, 0, 0, 0, flags)
    ints = {
        "numbones": (1, 156), "boneindex": (bone, 160), "bonecontrollerindex": (hitboxset, 168),
        "numhitboxsets": (1, 172), "hitboxsetindex": (hitboxset, 176), "numlocalanim": (1, 180),
        "localanimindex": (anim, 184), "numlocalseq": (1, 188), "localseqindex": (seq, 192),
        "numtextures": (nmesh, 204), "textureindex": (texture, 208), "numcdtextures": (1, 212),
        "cdtextureindex": (cd, 216), "numskinref": (nmesh, 220), "numskinfamilies": (1, 224), "skinindex": (skin, 228),
        "numbodyparts": (1, 232), "bodypartindex": (bodypart, 236), "localattachmentindex": (hitboxset, 244),
        "localnodeindex": (bodypart, 252), "localnodenameindex": (bodypart, 256),
    }
    for _k, (v, at) in ints.items():
        struct.pack_into("<i", out, at, v)
    for at in (264, 272, 280, 288, 296, 304, 324, 388):          # flex, ik, mouth, pose, iklock, flexui: none
        struct.pack_into("<i", out, at, mesh0)                     # (studiomdl points them at the meshes)
    struct.pack_into("<iii", out, 308, surf, keyvalue, 0)          # surfacepropindex, keyvalueindex, keyvaluesize
    struct.pack_into("<fi", out, 328, mass, 1)                     # mass, contents (solid)
    struct.pack_into("<i", out, 340, texture)                      # includemodelindex
    struct.pack_into("<i", out, 348, keyvalue)                     # szanimblocknameindex
    struct.pack_into("<i", out, 356, texture)                      # animblockindex
    struct.pack_into("<i", out, 364, bonetable)                    # bonetablebynameindex
    struct.pack_into("<i", out, 400, hdr2)                         # studiohdr2index
    struct.pack_into("<i", out, hdr2 + 4, keyvalue)                # (studiomdl: srcbonetransformindex -> "")
    return bytes(out)
