"""Nav mesh attribute marking.

L4D2 needs safe-room nav areas flagged (start room: PLAYER_START + CHECKPOINT,
end room: CHECKPOINT) or survivors won't spawn there and closing the end door
won't change level. nav_generate doesn't set these, and Hammer mappers normally
paint them by hand in-game. We generate a VScript that marks every nav area whose
centre lies in a region, then saves the nav mesh.

Verified in-game 2026-09-23: marking + nav_save + map reload makes the end door
trigger the transition.
"""
from __future__ import annotations

from dataclasses import dataclass

from . import geometry as g
from .entities import NAV_REGION
from .ir import MapIR

# TerrorNavArea spawn attribute bits
SPAWN_ATTRIBUTES = {
    "EMPTY": 2, "STOP_SCAN": 4, "BATTLESTATION": 32, "FINALE": 64, "PLAYER_START": 128,
    "BATTLEFIELD": 256, "IGNORE_VISIBILITY": 512, "NOT_CLEARABLE": 1024, "CHECKPOINT": 2048,
    "OBSCURED": 4096, "NO_MOBS": 8192, "THREAT": 16384, "RESCUE_VEHICLE": 32768,
    "RESCUE_CLOSET": 65536, "ESCAPE_ROUTE": 131072, "DOOR": 262144, "NOTHREAT": 524288,
    "LYINGDOWN": 1048576,
}

# Nav area centres sit slightly above the floor; pad regions so floor-level areas count.
PAD = 16.0


@dataclass
class NavRegion:
    mins: tuple[float, float, float]
    maxs: tuple[float, float, float]
    bits: int
    source: str = ""


def parse_attributes(text: str) -> tuple[int, list[str]]:
    bits, unknown = 0, []
    for word in text.replace(",", " ").replace("|", " ").upper().split():
        if word in SPAWN_ATTRIBUTES:
            bits |= SPAWN_ATTRIBUTES[word]
        else:
            unknown.append(word)
    return bits, unknown


def collect_regions(ir: MapIR) -> tuple[list[NavRegion], list[str]]:
    regions, problems = [], []
    for e in ir.entities:
        if e.classname == NAV_REGION:
            bits, unknown = parse_attributes(e.keyvalues.get("attributes", ""))
            if unknown:
                problems.append(f"Nav region '{e.source}': unknown attributes {', '.join(unknown)}")
        elif e.classname == "info_changelevel":
            bits = SPAWN_ATTRIBUTES["CHECKPOINT"]
        else:
            continue
        pts = [v for b in e.brushes for f in b.faces for v in f.verts]
        if not pts or not bits:
            continue
        mins, maxs = g.bounds(pts)
        regions.append(NavRegion(tuple(c - PAD for c in mins), tuple(c + PAD for c in maxs), bits, e.source))
    return regions, problems


def _vec(v) -> str:
    return f"Vector({v[0]:.1f}, {v[1]:.1f}, {v[2]:.1f})"


def navmark_script(regions: list[NavRegion], map_name: str) -> str:
    lines = [
        f"// Generated by Hammerless for {map_name}. Marks nav areas, then saves the nav mesh.",
        "local areas = {};",
        "NavMesh.GetAllAreas(areas);",
        "function HL_Mark(areas, mins, maxs, bits) {",
        "    local n = 0;",
        "    foreach (id, a in areas) {",
        "        local c = a.GetCenter();",
        "        if (c.x >= mins.x && c.x <= maxs.x && c.y >= mins.y && c.y <= maxs.y && c.z >= mins.z && c.z <= maxs.z) {",
        "            a.SetSpawnAttributes(a.GetSpawnAttributes() | bits);",
        "            n++;",
        "        }",
        "    }",
        "    return n;",
        "}",
    ]
    for r in regions:
        lines.append(f'printl("HAMMERLESS_NAVMARK {r.source}: " + HL_Mark(areas, {_vec(r.mins)}, {_vec(r.maxs)}, {r.bits}) + " areas");')
    lines.append('SendToConsole("nav_save");')
    lines.append('printl("HAMMERLESS_NAVMARK done");')
    return "\n".join(lines) + "\n"
