"""Nav mesh attribute marking.

L4D2 needs safe-room nav areas flagged (start room: PLAYER_START + CHECKPOINT,
end room: CHECKPOINT) or survivors won't spawn there and closing the end door
won't change level. nav_generate doesn't set these, and Hammer mappers normally
paint them by hand in-game. We generate a VScript that marks every nav area whose
centre lies in a region, then saves the nav mesh.

Verified in-game 2026-09-23: marking + nav_save + map reload makes the end door
trigger the transition.
"""
from __future__ import annotations

from dataclasses import dataclass

from . import geometry as g
from .entities import CLIMB, NAV_REGION, ZOMBIE_CLIMB_MAX
from .ir import Entity, MapIR

# TerrorNavArea spawn attribute bits
SPAWN_ATTRIBUTES = {
    "EMPTY": 2, "STOP_SCAN": 4, "BATTLESTATION": 32, "FINALE": 64, "PLAYER_START": 128,
    "BATTLEFIELD": 256, "IGNORE_VISIBILITY": 512, "NOT_CLEARABLE": 1024, "CHECKPOINT": 2048,
    "OBSCURED": 4096, "NO_MOBS": 8192, "THREAT": 16384, "RESCUE_VEHICLE": 32768,
    "RESCUE_CLOSET": 65536, "ESCAPE_ROUTE": 131072, "DOOR": 262144, "NOTHREAT": 524288,
    "LYINGDOWN": 1048576,
}

# Nav area centres sit slightly above the floor; pad regions so floor-level areas count.
# Not upward: nav_generate also covers the safe room's roof, just above the volume, and a
# roof area marked CHECKPOINT breaks the Director's flow (no wandering zombies).
PAD = 16.0


@dataclass
class NavRegion:
    mins: tuple[float, float, float]
    maxs: tuple[float, float, float]
    bits: int
    source: str = ""


def parse_attributes(text: str) -> tuple[int, list[str]]:
    bits, unknown = 0, []
    for word in text.replace(",", " ").replace("|", " ").upper().split():
        if word in SPAWN_ATTRIBUTES:
            bits |= SPAWN_ATTRIBUTES[word]
        else:
            unknown.append(word)
    return bits, unknown


def collect_regions(ir: MapIR) -> tuple[list[NavRegion], list[str]]:
    regions, problems = [], []
    for e in ir.entities:
        if e.classname == NAV_REGION:
            bits, unknown = parse_attributes(e.keyvalues.get("attributes", ""))
            if unknown:
                problems.append(f"Nav region '{e.source}': unknown attributes {', '.join(unknown)}")
        elif e.classname == "info_changelevel":
            bits = SPAWN_ATTRIBUTES["CHECKPOINT"]
        else:
            continue
        pts = [v for b in e.brushes for f in b.faces for v in f.verts]
        if not pts or not bits:
            continue
        mins, maxs = g.bounds(pts)
        regions.append(NavRegion(tuple(c - PAD for c in mins), (maxs[0] + PAD, maxs[1] + PAD, maxs[2]),
                                 bits, e.source))
    return regions, problems


@dataclass
class NavClimb:
    bottom: tuple[float, float, float]
    top: tuple[float, float, float]
    source: str = ""


def collect_climbs(ir: MapIR) -> tuple[list[NavClimb], list[str]]:
    """Pair up Zombie Climb points (same 'climb' name, one bottom and one top)."""
    ends: dict[str, dict[str, Entity]] = {}
    problems = []
    for e in ir.entities:
        if e.classname != CLIMB or e.origin is None:
            continue
        name = e.keyvalues.get("climb", "") or e.source
        end = e.keyvalues.get("end", "bottom").strip().lower()
        if end not in ("bottom", "top"):
            problems.append(f"Zombie Climb point '{e.source}': 'end' must be bottom or top")
            continue
        if end in ends.setdefault(name, {}):
            problems.append(f"Zombie Climb '{name}' has two {end} points; give each climb its own name")
        ends[name][end] = e
    climbs = []
    for name, pair in ends.items():
        if len(pair) < 2:
            problems.append(f"Zombie Climb '{name}' needs both a bottom and a top point")
            continue
        b, t = pair["bottom"].origin, pair["top"].origin
        if t[2] - b[2] > ZOMBIE_CLIMB_MAX:
            problems.append(f"Zombie Climb '{name}' is {t[2] - b[2]:.0f} units high; zombies only climb about "
                            f"{ZOMBIE_CLIMB_MAX:.0f}. Use a Zombie Ladder instead")
        climbs.append(NavClimb(tuple(b), tuple(t), name))
    return climbs, problems


def _vec(v) -> str:
    return f"Vector({v[0]:.1f}, {v[1]:.1f}, {v[2]:.1f})"


def climb_direction(bottom, top) -> int:
    """Nav direction (NORTH 0, EAST 1, SOUTH 2, WEST 3; +y is south) from bottom towards top."""
    dx, dy = top[0] - bottom[0], top[1] - bottom[1]
    return (1 if dx > 0 else 3) if abs(dx) > abs(dy) else (2 if dy > 0 else 0)


def navmark_script(regions: list[NavRegion], map_name: str, climbs: list[NavClimb] = (),
                   wall_climbs: bool = False) -> str:
    lines = [
        f"// Generated by Hammerless for {map_name}. Marks nav areas, then saves the nav mesh.",
        # (changing this line changes the file, which is what makes the next build rebuild the nav)
        f"// Zombies Climb Walls: {'on' if wall_climbs else 'off'}",
        "local areas = {};",
        "NavMesh.GetAllAreas(areas);",
        "function HL_Mark(areas, mins, maxs, bits) {",
        "    local n = 0;",
        "    foreach (id, a in areas) {",
        "        local c = a.GetCenter();",
        "        if (c.x >= mins.x && c.x <= maxs.x && c.y >= mins.y && c.y <= maxs.y && c.z >= mins.z && c.z <= maxs.z) {",
        "            a.SetSpawnAttributes(a.GetSpawnAttributes() | bits);",
        "            n++;",
        "        }",
        "    }",
        "    return n;",
        "}",
    ]
    for r in regions:
        lines.append(f'printl("HAMMERLESS_NAVMARK {r.source}: " + HL_Mark(areas, {_vec(r.mins)}, {_vec(r.maxs)}, {r.bits}) + " areas");')
    if climbs:
        lines += [
            "function HL_Area(p) {",
            "    local a = NavMesh.GetNavArea(p, 120.0);",
            "    return a != null ? a : NavMesh.GetNearestNavArea(p, 64.0, false, false);",
            "}",
            "function HL_Climb(bottom, top, dir) {",
            "    local lo = HL_Area(bottom), hi = HL_Area(top);",
            "    if (lo == null || hi == null || lo.GetID() == hi.GetID()) return \"failed (no nav mesh at an end)\";",
            "    lo.ConnectTo(hi, dir);",
            "    return \"linked\";",
            "}",
        ]
        for c in climbs:
            lines.append(f'printl("HAMMERLESS_NAVMARK climb {c.source}: " + HL_Climb({_vec(c.bottom)}, '
                         f'{_vec(c.top)}, {climb_direction(c.bottom, c.top)}));')
    lines.append('SendToConsole("nav_save");')
    lines.append('printl("HAMMERLESS_NAVMARK done");')
    return "\n".join(lines) + "\n"
